# Generated by Django 4.2.9 on 2024-02-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog_media/default.jpg', upload_to='blog_media/', verbose_name='Image'),
        ),
    ]
