# Generated by Django 3.2.19 on 2023-07-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230730_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
