# Generated by Django 3.2.19 on 2023-07-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog_media/default.jpg', upload_to='blog/'),
        ),
    ]
