# Generated by Django 3.2.20 on 2023-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230730_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog_media/default.jpg', upload_to=''),
        ),
    ]
