# Generated by Django 4.2.9 on 2024-02-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_date',)},
        ),
    ]
